version: '3'

services:

  app:
    build: 
      context: ./
      dockerfile: Dockerfile.node
    container_name: app
    networks: 
      - nodenet
    volumes: 
      - ./src:/usr/src/app
    tty: true
    depends_on: 
       - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ../mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - nodenet

  nginx:
    build:
      context: ./
      dockerfile: Dockerfile.nginx
    container_name: nginx
    networks:
      - nodenet
    ports:
      - "8080:80"
    depends_on:
      - app
      - db

networks:
  nodenet:
    driver: bridge